### ISSUE TITLE
No scrolling, error about "No scrolling pane found"

### ISSUE THREAD

**Issue by gPhantasm** [Cerlancism/discord-chat-replay#2]
When trying to use the script, the scrolling fails no matter how many parameters are specified or omitted. The error message it returns is "Chat scrolling pane not found".

![image](https://github.com/user-attachments/assets/974eeff8-b13e-4853-9534-017824b37cc1)

**Comment by Cerlancism** [comment]
I think discord has modified it's layout, will check if need to update the script

**Comment by Cerlancism** [comment]
Updated layout path and tested working
